apiVersion: apps/v1
kind: ReplicaSet
metadata:
  creationTimestamp: "2025-12-05T11:24:12Z"
  generation: 5
  name: new-replica-set
  namespace: default
  resourceVersion: "2434"
  uid: 9f682ae4-c458-4718-b2ff-3e5b19fd63da
spec:
  replicas: 2
  selector:
    matchLabels:
      name: busybox-pod
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: busybox-pod
    spec:
      containers:
      - command:
        - sh
        - -c
        - echo Hello Kubernetes! && sleep 3600
        image: busybox
        imagePullPolicy: Always
        name: busybox-container
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  fullyLabeledReplicas: 2
  observedGeneration: 5
  readyReplicas: 2
  replicas: 2