apiVersion: v1
kind: Pod

metadata:
  name: redis

spec:
  containers:
    - name: redis
      image: redis

# CRUD on k8s Pod object 

# kubectl create -f pod-definition-redis.yml
# kubectl describe pod redis

# kubectl get pod

# kubectl apply -f pod-definition-redis.yml

# kubectl delete pod redis