apiVersion: apps/v1
kind: ReplicaSet

metadata:
  name: my-replicaset
  labels:      # used to filter by kubectl, say filter via type: front-end
    app: my-app
    type: front-end

spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend

  template:

    metadata:
      name: nginx
      labels:
        app: nginx
        tier: frontend
    spec:
      containers:
        - name: nginx
          image: nginx


# CRUD on k8s ReplicaSet object 

# kubectl create -f replicaset-definition.yml
# kubectl describe replicaset new-replica-set

# kubectl get replicaset
# kubectl get rs

# kubectl edit replicaset my-replicaset
# kubectl replace -f replicaset-definition.yml

# kubectl delete replicaset my-replicaset
