apiVersion: v1
kind: Service

metadata:
  name: db
  namespace: vote
  labels:
    name: postgres-service
    app: voting-app

spec:
  selector:
    name: postgres-pod
    app: voting-app

  type: ClusterIP #Optional. Coz default is ClusterIP if not mentioned.

  ports:
    - port: 5432
      targetPort: 5432
