apiVersion: apps/v1
kind: Deployment

metadata:
  name: db
  namespace: vote
  labels:
    name: postgres-deploy
    app: voting-app

spec:
  replicas: 2
  selector:
    matchLabels:
      name: postgres-pod
      app: voting-app

  template:

    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod
        app: voting-app

    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine

          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD

            - name: POSTGRES_HOST_AUTH_METHOD # remove only this, if UN and PW based access is required like in prod 
              value: trust # NOT RECOMMENDED FOR PRODUCTION

          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data

          ports: 
            - containerPort: 5432

      volumes:
        - name: db-data
          emptyDir: {}