apiVersion: v1
kind: Service

metadata:
  name: redis
  namespace: vote
  labels:
    name: redis-service
    app: voting-app

spec:
  selector:
    name: redis-pod
    app: voting-app

  type: ClusterIP #Optional. Coz default is ClusterIP if not mentioned.

  ports:
    - port: 6379
      targetPort: 6379