apiVersion: v1
kind: Service

metadata:
  name: result
  namespace: vote
  labels:
    name: result-service
    app: voting-app

spec:
  selector:
    name: result-app-pod
    app: voting-app

  type: NodePort

  ports:
    - nodePort: 31001
      port: 8081
      targetPort: 80
