apiVersion: apps/v1
kind: Deployment

metadata:
  name: worker
  namespace: vote
  labels:
    name: worker-app-deploy
    app: voting-app

spec:
  replicas: 2
  selector:
    matchLabels:
      name: worker-app-pod
      app: voting-app

  template:

    metadata:
      name: worker-app-pod
      labels:
        name: worker-app-pod
        app: voting-app

    spec:
      containers:
        - name: worker-app
          image: dockersamples/examplevotingapp_worker