apiVersion: v1
kind: Service

metadata:
  name: db
  namespace: default
  labels:
    name: postgres-service
    app: voting-app

spec:
  selector:
    name: postgres-pod
    app: voting-app

  type: ClusterIP

  ports:
    - port: 5432
      targetPort: 5432
