apiVersion: apps/v1
kind: Deployment

metadata:
  name: postgres-deploy
  namespace: default
  labels:
    name: postgres-deploy
    app: voting-app

spec:
  replicas: 2
  selector:
    matchLabels:
      name: postgres-pod
      app: voting-app

  template:

    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod
        app: voting-app

    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD

          ports: 
            - containerPort: 5432