apiVersion: v1
kind: Service

metadata:
  name: redis
  namespace: default
  labels:
    name: redis-service
    app: voting-app

spec:
  selector:
    name: redis-pod
    app: voting-app

  type: ClusterIP

  ports:
    - port: 6379
      targetPort: 6379