apiVersion: v1
kind: Service

metadata:
  name: result-service
  namespace: default
  labels:
    name: result-service
    app: voting-app

spec:
  selector:
    name: result-app-pod
    app: voting-app

  type: NodePort

  ports:
    - nodePort: 30005
      port: 80
      targetPort: 80
