apiVersion: v1
kind: Service

metadata:
  name: voting-service
  namespace: default
  labels:
    name: voting-service
    app: voting-app

spec:
  selector:
    name: voting-app-pod
    app: voting-app

  type: NodePort

  ports:
    - nodePort: 30004
      port: 80
      targetPort: 80
